### ISSUE TITLE
mambabuild unable to find dependency on macOS ARM

### ISSUE THREAD

**Issue by jakirkham** [mamba-org/boa#203]
This `nss` [build]( https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=399117&view=logs&jobId=ced5d8de-8227-5f3f-33a1-45cf1592c45a&j=ced5d8de-8227-5f3f-33a1-45cf1592c45a&t=f7bcb349-6dca-53ba-d88d-1d9963e119ba ) (also [attached log]( https://github.com/mamba-org/boa/files/7437533/log_osx_arm64_20211028_2.txt )) from PR ( https://github.com/conda-forge/nss-feedstock/pull/45 ) ran into issues solving for the `nspr` dependency on macOS ARM. The same issue appears not to have occurred with conda-build.

**Comment by pkgw** [comment]
Related to this, conda-forge/poppler-feedstock#120 is currently failing due to this problem, but the error diagnostic makes it hard to determine this. I can totally understand why it might be hard to make this happen, but it would be very cool if the error message would "burrow down" to the lower-level cause and surface it.

**Comment by wolfv** [comment]
@pkgw yes, improving solver error messages is on our TODO list for next year (and we got funding for it, thanks to the CZI grant: https://wolfv.medium.com/the-mamba-project-and-the-czi-grant-ec88fb27c25
